--- 
- name: Setup Devpro Bastion Host
  hosts: localhost
  connection: local 
  gather_facts: no 
  tasks: 
    - name: Import VPC setup variable 
      include_vars: vars/vpc_setup

    - name: Import VPC setup Variable
      include_vars: vars/output_vars

    - name: Create Devpro ec2 key
      amazon.aws.ec2_key:
        name: devpro-key
        region: "{{region}}"
      register: key_out

    - name: Save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create Sec Grp for bastion host
      amazon.aws.ec2_security_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere and all port within sg
        vpc_id: "{{vpcid}}"
        region: "{{region}}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: "{{ item }}"
            rule_desc: allow SSH from specified IPs
      with_items: "{{ MYIP }}"
      register: BastionSG_out

    - name: Create security group with specific IP address allowed
      amazon.aws.ec2_security_group:
        name: ansible_controller_sg
        description: Ansible controller security group
        region: "{{ region }}"
        vpc_id: "{{ vpcid }}"
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: 192.168.0.133/32
            rule_desc: Allow SSH from 192.168.0.133
      register: ansible_controller_sg_out

    - name: Creating Bastion Host
      amazon.aws.ec2_instance:
        key_name: devpro-key
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        tags:
          Name: "Bastion_host"
          Project: Devpro
          Owner: DevOps Team 
        exact_count: 1
        security_group: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out

    - name: Insert/Update "BastionSGid" in vars/output_vars
      ansible.builtin.blockinfile:
        path: vars/output_vars
        backup: yes
        block: |
          BastionSGid: {{BastionSG_out.group_id}}


