---
- name: Create EC2 instances
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    instance_type: t2.micro
    ami: ami-0c94855ba95c71c99
    region: us-east-1
    keypair: my-keypair
    sg_name: my-security-group
    sg_description: My security group
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

  tasks:
  - name: Create a security group
    amazon.aws.ec2_security_group:
      name: "{{ sg_name }}"
      description: "{{ sg_description }}"
      region: "{{ region }}"
      rules: "{{ rules }}"
    register: security_group

  - name: Create a key pair
    community.aws.ec2_key:
      name: "{{ keypair }}"
      region: "{{ region }}"
    register: keypair

  - name: Launch an EC2 Instance
    community.aws.ec2:
      key_name: "{{ keypair.key.name }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ ami }}"
      region: "{{ region }}"
      group_id: "{{ security_group.group_id }}"
      count: 1
      wait: true
      instance_tags:
        Name: my-instance



