---
- name: Launch EC2 instance
  hosts: localhost
  gather_facts: false
  vars:
    region: "us-east-1"
    instance_type: "t2.micro"
    image_id: "ami-0e58f89e91723af4c"
    subnet_id: "subnet-0582e4bc11a2ab0d4"
    security_group: "Demo_security_group"
    key_name: "demo_key"
    instance_tags:
      Name: "Demo_instance"
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ image_id }}"
        subnet_id: "{{ subnet_id }}"
        security_groups: "{{ security_group }}"
        key_name: "{{ key_name }}"
        instance_tags: "{{ instance_tags }}"
        wait: true
        count: 1
        state: present
      register: ec2
    - name: Show instance details
      debug:
        var: ec2.instance_ids[0]

