---
- name: Create EC2 instances
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    instance_type: t2.micro
    ami: ami-0c94855ba95c71c99
    region: us-east-1
    keypair: my-keypair
    sg_name: my-security-group
    sg_description: My security group
    vpc_subnet_id: subnet-0582e4bc11a2ab0d4
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

  tasks:
  - name: Create a security group
    amazon.aws.ec2_security_group:
      name: "{{ sg_name }}"
      description: "{{ sg_description }}"
      region: "{{ region }}"
      rules: "{{ rules }}"
    register: security_group

  - name: Create a key pair
    amazon.aws.ec2_key:
      name: "{{ keypair }}"
      region: "{{ region }}"
    register: keypair

  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      key_name: "{{ keypair.key.name }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      instance_type: "{{ instance_type }}"
      security_group: "{{ security_group.group_id }}"
      network:
        assign_public_ip: true
      image_id: "{{ ami }}"
      tags:
        Environment: Testing

  - debug:
      var: ec2_instance

