- name: Launch EC2 instances on AWS
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        key_name: demo_key
        instance_type: t2.micro
        image:
          id: ami-0e58f89e91723af4c
        wait: yes
        count: 1
        vpc_subnet_id: subnet-0582e4bc11a2ab0d4
        region: us-east-1
        instance_tags:
          Name: Demo_instance
        state: present
      register: ec2

    - name: Display the created instance details
      debug:
        var: ec2


