---
- hosts: localhost
  gather_facts: false

  tasks:
    - name: Launch EC2 instance
      ec2_instance:
        image_id: ami-0e58f89e91723af4c
        instance_type: t2.micro
        key_name: demo_key
        security_groups:
          - Demo_security_group
        subnet_id: subnet-0582e4bc11a2ab0d4
        instance_tags:
          Name: Demo_instance
        wait: true
        region: us-east-1
      register: ec2

    - name: Add new instance to host group
      add_host:
        name: "{{ item.public_ip }}"
        groups: launched
      with_items: "{{ ec2.instances }}"
